services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    command: sleep infinity
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: vehicle_management_db
      MYSQL_USER: root
      MYSQL_PASSWORD: student
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: vehicle_management_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
